// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9v9VRNdg1bUar-ZcAMxUTRAvPuhoFxg4',
    appId: '1:451097066871:web:b40e742211fe762db8b572',
    messagingSenderId: '451097066871',
    projectId: 'fir-project-6597d',
    authDomain: 'fir-project-6597d.firebaseapp.com',
    storageBucket: 'fir-project-6597d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWX_gAPO6bsqPH4ajq8LDj5nd_Pm4Hag',
    appId: '1:451097066871:android:f7fd607100573dbab8b572',
    messagingSenderId: '451097066871',
    projectId: 'fir-project-6597d',
    storageBucket: 'fir-project-6597d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxBmRtw1PjyOxmRazb-gXCTh8tOUtZUKU',
    appId: '1:451097066871:ios:df3fa43291160084b8b572',
    messagingSenderId: '451097066871',
    projectId: 'fir-project-6597d',
    storageBucket: 'fir-project-6597d.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBmRtw1PjyOxmRazb-gXCTh8tOUtZUKU',
    appId: '1:451097066871:ios:11892e60d02d0e75b8b572',
    messagingSenderId: '451097066871',
    projectId: 'fir-project-6597d',
    storageBucket: 'fir-project-6597d.appspot.com',
    iosBundleId: 'com.example.loginFirebase.RunnerTests',
  );
}
